
name: iOS unsigned IPA (no signing)
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'

      - name: Generate iOS/Android folders
        run: flutter create .

      - name: Patch Info.plist & bundle id
        run: |
          /usr/libexec/PlistBuddy -c 'Add :NSMicrophoneUsageDescription string "Analyze pet sounds on-device."' ios/Runner/Info.plist || true
          /usr/libexec/PlistBuddy -c 'Add :NSCameraUsageDescription string "Analyze pet facial expressions on-device."' ios/Runner/Info.plist || true
          /usr/libexec/PlistBuddy -c 'Add :UIBackgroundModes array' ios/Runner/Info.plist || true
          /usr/libexec/PlistBuddy -c 'Add :UIBackgroundModes:0 string audio' ios/Runner/Info.plist || true
          sed -i.bak -E 's/PRODUCT_BUNDLE_IDENTIFIER = [^;]+;/PRODUCT_BUNDLE_IDENTIFIER = com.petmood.radar;/g' ios/Runner.xcodeproj/project.pbxproj || true

      - name: CocoaPods install
        run: |
          cd ios
          pod install --repo-update || true

      - name: flutter pub get
        run: flutter pub get

      - name: Generate app icons
        run: |
          flutter pub run flutter_launcher_icons

      - name: Build .app (no codesign)
        run: |
          xcodebuild -workspace ios/Runner.xcworkspace             -scheme Runner -configuration Release -sdk iphoneos             CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO CODE_SIGNING_IDENTITY=""             build

      - name: Package IPA
        run: |
          APP_PATH=$(find build/ios -type d -name "Runner.app" | head -n 1)
          mkdir -p Payload
          cp -R "$APP_PATH" Payload/Runner.app
          zip -r PetMoodRadar-unsigned.ipa Payload

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: PetMoodRadar-unsigned-ipa
          path: PetMoodRadar-unsigned.ipa
