name: iOS unsigned IPA (stable flutter build)
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'     # стабильный канал
          cache: true

      - name: Flutter doctor
        run: flutter doctor -v

      - name: Ensure project scaffolding (ios/android)
        run: flutter create .

      - name: Patch Info.plist & bundle id
        run: |
          /usr/libexec/PlistBuddy -c 'Add :NSMicrophoneUsageDescription string "Analyze pet sounds on-device."' ios/Runner/Info.plist || true
          /usr/libexec/PlistBuddy -c 'Add :NSCameraUsageDescription string "Analyze pet facial expressions on-device."' ios/Runner/Info.plist || true
          /usr/libexec/PlistBuddy -c 'Add :UIBackgroundModes array' ios/Runner/Info.plist || true
          /usr/libexec/PlistBuddy -c 'Add :UIBackgroundModes:0 string audio' ios/Runner/Info.plist || true
          sed -i.bak -E 's/PRODUCT_BUNDLE_IDENTIFIER = [^;]+;/PRODUCT_BUNDLE_IDENTIFIER = com.petmood.radar;/g' ios/Runner.xcodeproj/project.pbxproj || true

      - name: Install Ruby & CocoaPods
        run: |
          sudo gem install cocoapods -N
          pod --version

      - name: Flutter pub get
        run: flutter pub get

      - name: Generate app icons
        run: flutter pub run flutter_launcher_icons

      - name: Install Pods
        working-directory: ios
        # частые падения из-за CDN — делаем retry и без repo-update
        run: |
          set -e
          pod install --repo-update || pod install || (pod repo update && pod install)

      - name: Build iOS (no codesign)
        # это самый надёжный путь получить Runner.app без подписания
        run: flutter build ios --release --no-codesign

      - name: Package unsigned IPA
        run: |
          APP_PATH=$(find build/ios -type d -name "Runner.app" | head -n 1)
          if [ -z "$APP_PATH" ]; then
            APP_PATH="build/ios/iphoneos/Runner.app"
          fi
          mkdir -p Payload
          cp -R "$APP_PATH" Payload/Runner.app
          zip -r PetMoodRadar-unsigned.ipa Payload

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: PetMoodRadar-unsigned-ipa
          path: PetMoodRadar-unsigned.ipa
