name: iOS unsigned IPA (no signing)
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14  # Apple Silicon (arm64)
    steps:
      - uses: actions/checkout@v4

      # ✅ Пинним Flutter и архитектуру arm64 для macos-14
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'   # зафиксируй стабильную версию (можно 3.22.x/3.24.x, если знаешь точную)
          architecture: 'arm64'
          cache: true

      - name: flutter --version
        run: flutter --version

      - name: Generate iOS/Android folders
        run: flutter create .

      - name: Patch Info.plist & bundle id
        run: |
          /usr/libexec/PlistBuddy -c 'Add :NSMicrophoneUsageDescription string "Analyze pet sounds on-device."' ios/Runner/Info.plist || true
          /usr/libexec/PlistBuddy -c 'Add :NSCameraUsageDescription string "Analyze pet facial expressions on-device."' ios/Runner/Info.plist || true
          /usr/libexec/PlistBuddy -c 'Add :UIBackgroundModes array' ios/Runner/Info.plist || true
          /usr/libexec/PlistBuddy -c 'Add :UIBackgroundModes:0 string audio' ios/Runner/Info.plist || true
          sed -i.bak -E 's/PRODUCT_BUNDLE_IDENTIFIER = [^;]+;/PRODUCT_BUNDLE_IDENTIFIER = com.petmood.radar;/g' ios/Runner.xcodeproj/project.pbxproj || true

      - name: flutter pub get
        run: flutter pub get

      # автогенерация иконок (мы добавляли ранее)
      - name: Generate app icons
        run: |
          flutter pub run flutter_launcher_icons

      # на всякий случай: CocoaPods (иногда зеркало тупит; шаг помечен || true)
      - name: CocoaPods install
        run: |
          cd ios
          pod install --repo-update || true

      - name: Build .app (no codesign)
        run: |
          xcodebuild -workspace ios/Runner.xcworkspace \
            -scheme Runner -configuration Release -sdk iphoneos \
            CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO CODE_S_
