name: iOS unsigned IPA (stable+robust)
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Flutter (stable)
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'
          cache: true

      - name: Versions
        run: |
          flutter --version
          dart --version
          xcodebuild -version || true
          sw_vers

      - name: Ensure iOS/Android scaffolding
        run: |
          flutter create .
          # иногда полезно «освежить» ios-папку
          rm -rf ios/Flutter/Flutter.podspec || true

      - name: Patch Info.plist & bundle id
        run: |
          /usr/libexec/PlistBuddy -c 'Add :NSMicrophoneUsageDescription string "Analyze pet sounds on-device."' ios/Runner/Info.plist || true
          /usr/libexec/PlistBuddy -c 'Add :NSCameraUsageDescription string "Analyze pet facial expressions on-device."' ios/Runner/Info.plist || true
          /usr/libexec/PlistBuddy -c 'Add :UIBackgroundModes array' ios/Runner/Info.plist || true
          /usr/libexec/PlistBuddy -c 'Add :UIBackgroundModes:0 string audio' ios/Runner/Info.plist || true
          sed -i.bak -E 's/PRODUCT_BUNDLE_IDENTIFIER = [^;]+;/PRODUCT_BUNDLE_IDENTIFIER = com.petmood.radar;/g' ios/Runner.xcodeproj/project.pbxproj || true

      - name: Set iOS deployment target (Podfile = 13.0)
        run: |
          cat > ios/Podfile <<'POD'
          platform :ios, '13.0'
          use_frameworks!
          use_modular_headers!

          target 'Runner' do
            flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
          end

          post_install do |installer|
            installer.pods_project.targets.each do |target|
              target.build_configurations.each do |config|
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
              end
            end
          end
          POD

      - name: Install Ruby & CocoaPods
        run: |
          sudo gem install cocoapods -N
          pod --version

      - name: Flutter pub get
        run: flutter pub get

      - name: Generate app icons
        run: flutter pub run flutter_launcher_icons

      - name: CocoaPods install (with retries)
        working-directory: ios
        shell: bash
        run: |
          set -e
          tries=0
          until [ $tries -ge 3 ]; do
            pod repo update && pod install && break
            tries=$((tries+1))
            echo "Retry $tries in 15s..."
            sleep 15
          done
          pod deintegrate || true
          pod install

      - name: Clean flutter build
        run: flutter clean

      - name: Build iOS (no codesign)
        run: flutter build ios --release --no-codesign

      - name: Package unsigned IPA
        run: |
          APP_PATH=$(find build/ios -type d -name "Runner.app" | head -n 1)
          if [ -z "$APP_PATH" ]; then
            APP_PATH="build/ios/iphoneos/Runner.app"
          fi
          echo "Using APP_PATH=$APP_PATH"
          mkdir -p Payload
          cp -R "$APP_PATH" Payload/Runner.app
          zip -r PetMoodRadar-unsigned.ipa Payload

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: PetMoodRadar-unsigned-ipa
          path: PetMoodRadar-unsigned.ipa
